version: "3.7"
networks:
  application:
volumes:
  dbdata:
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/app
      - ./config/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - application
    depends_on:
      - fpm
  fpm:
    image: php:8.3.0-fpm
    networks:
      - application
    volumes:
      - ./src:/app
  db:
    image: mysql:8
    networks:
      - application
    volumes:
      - dbdata:/var/lib/mysql
      - ./config/mysql-entrypoint:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - 3306:3306